"""password_field_adjust2

Revision ID: 04947097add0
Revises: 93153c7d643d
Create Date: 2025-10-11 22:42:46.890552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04947097add0'
down_revision: Union[str, Sequence[str], None] = '93153c7d643d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('useremail', sa.String(length=30), nullable=False),
    sa.Column('userpassword', sa.String(), nullable=False),
    sa.Column('createdat', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('useremail'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['owner'], ['userid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'users', ['userid'], ['userid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
