"""add_vote_table

Revision ID: 7425de80a4fb
Revises: 96b427b8f2c4
Create Date: 2025-10-11 22:12:20.494143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7425de80a4fb'
down_revision: Union[str, Sequence[str], None] = '96b427b8f2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('productid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productid', 'userid')
    )
    op.add_column('products', sa.Column('productcreated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'productdelivered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('products', 'createdat')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'phone')
    op.add_column('products', sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('products', 'productdelivered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('products', 'productcreated')
    op.drop_table('votes')
    # ### end Alembic commands ###
