"""password_field_adjust

Revision ID: 93153c7d643d
Revises: 5a912c715887
Create Date: 2025-10-11 22:36:55.588918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93153c7d643d'
down_revision: Union[str, Sequence[str], None] = '5a912c715887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
