"""autocreate_tables

Revision ID: de55c654acbd
Revises: 61a60c9c81d0
Create Date: 2025-10-12 22:52:31.372731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de55c654acbd'
down_revision: Union[str, Sequence[str], None] = '61a60c9c81d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('useremail', sa.String(length=30), nullable=False),
    sa.Column('userpassword', sa.String(), nullable=False),
    sa.Column('createdat', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('useremail'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.create_table('products',
    sa.Column('productid', sa.INTEGER(), nullable=False),
    sa.Column('productname', sa.String(), nullable=False),
    sa.Column('productdescription', sa.String(), nullable=True),
    sa.Column('productdelivered', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('productcreated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productid')
    )
    op.create_index(op.f('ix_products_productid'), 'products', ['productid'], unique=False)
    op.create_table('votes',
    sa.Column('productid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['products.productid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productid', 'userid')
    )
    op.drop_index(op.f('ix_student_studnetid'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('studnetid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('studnetid', name=op.f('student_pkey'))
    )
    op.create_index(op.f('ix_student_studnetid'), 'student', ['studnetid'], unique=False)
    op.drop_table('votes')
    op.drop_index(op.f('ix_products_productid'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
