name: Test and deploy code
on:
   push :
     branches : ["main"]
   pull_request :
      branches : ["main"]



jobs:
  dummyfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: check code being pushed
        uses: actions/checkout@v2
      - name: print that code  is reached
        run: echo "your code is on github succefully"
  
