name: Test and deploy code
on:
   push :
     branches : ["main"]
   pull_request :
      branches : ["main"]



jobs:
  dummyfirstjob:
    environment:
      name: testingenv
    env:

      DBPASSWORD: ${{secrets.DBPASSWORD}}
      DBHOST: ${{secrets.DBHOST}}
      DBPORT: ${{secrets.DBPORT}}
      DBNAME: ${{secrets.DBNAME}}
      DBUSERNAME: ${{secrets.DBUSERNAME}}
      SECRETKEY: ${{secrets.SECRETKEY}}
      ACCESS_TOKEN_EXPIRES_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRES_MINUTES}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      DBURL: ${{secrets.DBURL}}

    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.DBUSERNAME}}
          POSTGRES_PASSWORD: ${{secrets.DBPASSWORD}}
          POSTGRES_DB: ${{secrets.DBNAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:


        
      - name: check code being pushed
        uses: actions/checkout@v2
      - name: pulling python version 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12' 
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name : Run tests on ubuntu machines
        run: pytest




  
